### ISSUE TITLE
Implement filtration functionality for the dashboards

### ISSUE THREAD

**Issue by Arnold-CK** [Arnold-CK/fraternity-trust-fund#1]
### Description
For the dashboard to age with grace, there is need for a user to be able to filter it.

### To-Do

- [ ] Put default values for the filters
- [ ] Put a filter button that implements filtration
- [ ] Implement functionality that returns a filtered dashboard
